// Localized labels for the treatment report. Only fixed labels/headings are translated;
// the doctor's typed notes and treatment text stay exactly as written (offline, no wifi).
import type { Language, ToothConditionKey, NoteType, TreatmentPriority } from './types'

export interface ReportStrings {
  dir: 'ltr' | 'rtl'
  title: string
  patient: string
  patientId: string
  dob: string
  age: string
  examDate: string
  provider: string
  reportDate: string
  phoneWord: string
  licenseWord: string
  medicalAlerts: string
  allergies: string
  conditions: string
  medications: string
  patientSummary: string
  ageWord: string
  relevantDental: string
  examFindings: string
  noConditions: string
  teethWord: string
  conditionLabels: Record<ToothConditionKey, string>
  clinicalNotes: string
  noteTypes: Record<NoteType, string>
  teethLabel: string
  treatmentPlan: string
  thPriority: string
  thTooth: string
  thTreatment: string
  thTimeline: string
  thCost: string
  priority: Record<TreatmentPriority, string>
  summary: string
  providerApproval: string
  approved: string
  pending: string
  patientAck: string
  dateLine: string
  generatedBy: string
  upper: string
  lower: string
}

export const REPORT_STRINGS: Record<Language, ReportStrings> = {
  english: {
    dir: 'ltr',
    title: 'Dental Examination & Treatment Report',
    patient: 'Patient',
    patientId: 'Patient ID',
    dob: 'Date of Birth',
    age: 'Age',
    examDate: 'Exam Date',
    provider: 'Provider',
    reportDate: 'Report Date',
    phoneWord: 'Phone',
    licenseWord: 'License #',
    medicalAlerts: 'Medical Alerts',
    allergies: 'Allergies',
    conditions: 'Conditions',
    medications: 'Medications',
    patientSummary: 'Patient Summary',
    ageWord: 'age',
    relevantDental: 'Relevant dental history:',
    examFindings: 'Examination Findings',
    noConditions: 'No conditions recorded.',
    teethWord: 'teeth',
    conditionLabels: {
      unexamined: 'Unexamined',
      healthy: 'Healthy',
      cavity: 'Cavity',
      filled: 'Filled',
      missing: 'Missing',
      implant: 'Implant',
      treatment: 'Needs Treatment'
    },
    clinicalNotes: 'Clinical Notes',
    noteTypes: {
      finding: 'Examination Findings',
      treatment_plan: 'Treatment Plan Notes',
      follow_up: 'Follow-up',
      observation: 'Special Observations'
    },
    teethLabel: 'Teeth',
    treatmentPlan: 'Treatment Plan',
    thPriority: 'Priority',
    thTooth: 'Tooth',
    thTreatment: 'Recommended Treatment',
    thTimeline: 'Estimated Timeline',
    thCost: 'Est. Cost',
    priority: { urgent: 'urgent', important: 'important', routine: 'routine' },
    summary: 'Summary',
    providerApproval: 'Provider Signature / Approval',
    approved: 'Approved',
    pending: 'Pending approval',
    patientAck: 'Patient Acknowledgement (optional)',
    dateLine: 'Date',
    generatedBy: 'Generated by Giving Smiles on',
    upper: 'UPPER',
    lower: 'LOWER'
  },

  spanish: {
    dir: 'ltr',
    title: 'Informe de Examen y Plan de Tratamiento Dental',
    patient: 'Paciente',
    patientId: 'ID del Paciente',
    dob: 'Fecha de Nacimiento',
    age: 'Edad',
    examDate: 'Fecha del Examen',
    provider: 'Proveedor',
    reportDate: 'Fecha del Informe',
    phoneWord: 'Teléfono',
    licenseWord: 'N.º de Licencia',
    medicalAlerts: 'Alertas Médicas',
    allergies: 'Alergias',
    conditions: 'Condiciones',
    medications: 'Medicamentos',
    patientSummary: 'Resumen del Paciente',
    ageWord: 'edad',
    relevantDental: 'Historial dental relevante:',
    examFindings: 'Hallazgos del Examen',
    noConditions: 'No se registraron condiciones.',
    teethWord: 'dientes',
    conditionLabels: {
      unexamined: 'No examinado',
      healthy: 'Sano',
      cavity: 'Caries',
      filled: 'Empastado',
      missing: 'Ausente',
      implant: 'Implante',
      treatment: 'Necesita Tratamiento'
    },
    clinicalNotes: 'Notas Clínicas',
    noteTypes: {
      finding: 'Hallazgos del Examen',
      treatment_plan: 'Notas del Plan de Tratamiento',
      follow_up: 'Seguimiento',
      observation: 'Observaciones Especiales'
    },
    teethLabel: 'Dientes',
    treatmentPlan: 'Plan de Tratamiento',
    thPriority: 'Prioridad',
    thTooth: 'Diente',
    thTreatment: 'Tratamiento Recomendado',
    thTimeline: 'Plazo Estimado',
    thCost: 'Costo Est.',
    priority: { urgent: 'urgente', important: 'importante', routine: 'rutina' },
    summary: 'Resumen',
    providerApproval: 'Firma / Aprobación del Proveedor',
    approved: 'Aprobado',
    pending: 'Pendiente de aprobación',
    patientAck: 'Reconocimiento del Paciente (opcional)',
    dateLine: 'Fecha',
    generatedBy: 'Generado por Giving Smiles el',
    upper: 'SUPERIOR',
    lower: 'INFERIOR'
  },

  arabic: {
    dir: 'rtl',
    title: 'تقرير الفحص وخطة العلاج السني',
    patient: 'المريض',
    patientId: 'رقم المريض',
    dob: 'تاريخ الميلاد',
    age: 'العمر',
    examDate: 'تاريخ الفحص',
    provider: 'مقدم الخدمة',
    reportDate: 'تاريخ التقرير',
    phoneWord: 'الهاتف',
    licenseWord: 'رقم الترخيص',
    medicalAlerts: 'تنبيهات طبية',
    allergies: 'الحساسية',
    conditions: 'الحالات',
    medications: 'الأدوية',
    patientSummary: 'ملخص المريض',
    ageWord: 'العمر',
    relevantDental: 'التاريخ السني ذو الصلة:',
    examFindings: 'نتائج الفحص',
    noConditions: 'لم تُسجَّل أي حالات.',
    teethWord: 'الأسنان',
    conditionLabels: {
      unexamined: 'غير مفحوص',
      healthy: 'سليم',
      cavity: 'تسوس',
      filled: 'محشو',
      missing: 'مفقود',
      implant: 'زرعة',
      treatment: 'يحتاج علاج'
    },
    clinicalNotes: 'الملاحظات السريرية',
    noteTypes: {
      finding: 'نتائج الفحص',
      treatment_plan: 'ملاحظات خطة العلاج',
      follow_up: 'المتابعة',
      observation: 'ملاحظات خاصة'
    },
    teethLabel: 'الأسنان',
    treatmentPlan: 'خطة العلاج',
    thPriority: 'الأولوية',
    thTooth: 'السن',
    thTreatment: 'العلاج الموصى به',
    thTimeline: 'الإطار الزمني المقدَّر',
    thCost: 'التكلفة التقديرية',
    priority: { urgent: 'عاجل', important: 'مهم', routine: 'روتيني' },
    summary: 'الملخص',
    providerApproval: 'توقيع / اعتماد مقدم الخدمة',
    approved: 'مُعتمد',
    pending: 'بانتظار الاعتماد',
    patientAck: 'إقرار المريض (اختياري)',
    dateLine: 'التاريخ',
    generatedBy: 'تم الإنشاء بواسطة Giving Smiles في',
    upper: 'العلوي',
    lower: 'السفلي'
  }
}
